/**
 * Auth flows — owner login, staff PIN login, permission gates, logout.
 */
import { test, expect } from './helpers/cleanup'
import type { Page } from '@playwright/test'
import fs from 'fs'

const VENUE = process.env.TEST_VENUE_SLUG ?? 'brew-and-bloom'

// Generated by global-setup, and gitignored, so it is absent unless someone
// has run that with TEST_OWNER_EMAIL / TEST_OWNER_PASSWORD set. Without it
// Playwright cannot build the context at all and the tests below failed in
// milliseconds, before running a single line — four permanent red results
// that looked like product breakage but were only missing credentials.
// Skipping when it is absent keeps the signal honest.
const OWNER_STATE     = 'tests/auth/owner-state.json'
const hasOwnerState   = fs.existsSync(OWNER_STATE)
const NEEDS_OWNER_MSG = `Requires ${OWNER_STATE} — run global-setup with TEST_OWNER_EMAIL and TEST_OWNER_PASSWORD set`

async function openOwnerLoginForm(page: Page) {
  // Fast-forward the 5.2s entrance animation so inputs become interactive immediately.
  await page.evaluate(() => window.dispatchEvent(new Event('pk-splash-done')))
  const emailInput = page.locator('input[type="email"]').first()
  await emailInput.waitFor({ state: 'visible', timeout: 8000 })
  return emailInput
}

test.describe('Owner login', () => {
  test.use({ storageState: { cookies: [], origins: [] } })

  test('shows login page at /login', async ({ page }) => {
    await page.goto('/login')
    const emailInput = await openOwnerLoginForm(page)
    // Brand is an SVG logo; verify the sign-in form fields are present
    await expect(emailInput).toBeVisible()
    await expect(page.locator('input[type="password"]').first()).toBeVisible()
    await expect(page.getByRole('button', { name: /^Sign In$/i })).toBeVisible()
  })

  test('shows error on wrong credentials', async ({ page }) => {
    await page.goto('/login')
    const emailInput = await openOwnerLoginForm(page)
    await emailInput.fill('wrong@example.com')
    await page.locator('input[type="password"]:visible').first().fill('wrongpassword')
    // Case-insensitive, matching the assertion in the test above. This was
    // /^Sign In$/ — case-sensitive — so it stopped matching the button's
    // actual "Sign in" label and the click timed out on every run.
    await page.getByRole('button', { name: /^sign in$/i }).click()
    await expect(page.getByText(/invalid|incorrect|error/i).first()).toBeVisible({ timeout: 8000 })
  })
})

test.describe('Staff PIN login', () => {
  // Use owner-only auth (Supabase session, no PIN session) so we see the tiles.
  // Fall back to an empty state when the file is absent so the context can
  // still be built — the skip below is what actually stops these running.
  test.use({ storageState: hasOwnerState ? OWNER_STATE : { cookies: [], origins: [] } })
  test.skip(!hasOwnerState, NEEDS_OWNER_MSG)

  test('shows staff tiles at venue login page', async ({ page }) => {
    await page.goto(`/v/${VENUE}`)
    await page.waitForLoadState('networkidle')
    await expect(page.getByText('Sarah Mitchell')).toBeVisible({ timeout: 10000 })
    await expect(page.getByText("James O'Brien")).toBeVisible()
  })

  test('shows PIN pad after selecting a staff member', async ({ page }) => {
    await page.goto(`/v/${VENUE}`)
    await page.waitForLoadState('networkidle')
    await page.getByText('Sarah Mitchell').click()
    await expect(page.locator('input[type="password"]').first()).toBeVisible({ timeout: 5000 })
  })

  test('shows error on wrong PIN', async ({ page }) => {
    await page.goto(`/v/${VENUE}`)
    await page.waitForSelector('text=Sarah Mitchell', { timeout: 15000 })
    await page.getByText('Sarah Mitchell').first().click()
    await page.waitForSelector('input[type="password"]', { timeout: 5000 })
    await page.locator('input[type="password"]').fill('9999')
    // Auto-submits on 4 digits — just wait for the inline error
    await expect(page.getByText(/incorrect/i)).toBeVisible({ timeout: 8000 })
  })

  test('successful PIN login redirects to dashboard', async ({ page }) => {
    await page.goto(`/v/${VENUE}`)
    await page.waitForSelector('text=Sarah Mitchell', { timeout: 15000 })
    await page.getByText('Sarah Mitchell').first().click()
    await page.waitForSelector('input[type="password"]', { timeout: 5000 })
    await page.locator('input[type="password"]').fill('1234')
    // Auto-submits on 4 digits — wait for navigation directly
    await page.waitForURL(`**/v/${VENUE}/dashboard**`, { timeout: 15000 })
    await expect(page).toHaveURL(new RegExp(`/v/${VENUE}/dashboard`))
  })
})

test.describe('404 page', () => {
  test.use({ storageState: { cookies: [], origins: [] } })

  test('shows 404 for unknown routes', async ({ page }) => {
    await page.goto('/this-does-not-exist-at-all')
    await expect(page.getByText(/404|not found/i).first()).toBeVisible()
  })
})
