export const DEFAULT_TODAY_ITEMS = ['on_shift', 'opening_checks', 'fridge_checks', 'cleaning_tasks', 'critical_actions', 'pending_leave']

export const TODAY_ITEM_REGISTRY = {
  on_shift: {
    id: 'on_shift',
    label: 'Staff on shift',
    description: 'How many staff are rotaed today',
    feature: 'rota',
    metric: summary => summary.onShiftToday,
    metricLabel: 'On shift',
  },
  opening_checks: {
    id: 'opening_checks',
    label: 'Opening / closing checks',
    description: 'Daily opening and closing completion',
    feature: 'opening_closing',
    metric: summary => summary.checksToday,
    metricLabel: 'Checks done',
    action: (summary, vp) => summary.checksToday === 0 && { label: 'Opening checks not done', to: vp('/opening-closing'), urgency: 'warn' },
  },
  fridge_checks: {
    id: 'fridge_checks',
    label: 'Fridge / freezer checks',
    description: 'Fridges that still need a reading today',
    feature: 'fridge',
    metric: summary => summary.uncheckedFridges,
    metricLabel: 'Fridges due',
    dangerWhenPositive: true,
    action: (summary, vp) => summary.uncheckedFridges > 0 && { label: `${summary.uncheckedFridges} fridge${summary.uncheckedFridges > 1 ? 's' : ''} not logged today`, to: vp('/fridge'), urgency: 'warn' },
  },
  cooking_temps: {
    id: 'cooking_temps',
    label: 'Cooking temps',
    description: 'Whether cooking temperatures have been recorded today',
    feature: 'cooking_temps',
    metric: summary => summary.cookingTempsToday,
    metricLabel: 'Cooking logs',
    action: (summary, vp) => summary.cookingTempsToday === 0 && { label: 'Cooking temps not recorded today', to: vp('/cooking-temps'), urgency: 'warn' },
  },
  hot_holding: {
    id: 'hot_holding',
    label: 'Hot holding',
    description: 'Whether hot holding checks have been recorded today',
    feature: 'hot_holding',
    metric: summary => summary.hotHoldingToday,
    metricLabel: 'Hot hold logs',
    action: (summary, vp) => summary.hotHoldingToday === 0 && { label: 'Hot holding not recorded today', to: vp('/hot-holding'), urgency: 'warn' },
  },
  cooling_logs: {
    id: 'cooling_logs',
    label: 'Cooling logs',
    description: 'Whether cooling logs have been recorded today',
    feature: 'cooling_logs',
    metric: summary => summary.coolingLogsToday,
    metricLabel: 'Cooling logs',
    action: (summary, vp) => summary.coolingLogsToday === 0 && { label: 'Cooling logs not recorded today', to: vp('/cooling-logs'), urgency: 'warn' },
  },
  cleaning_tasks: {
    id: 'cleaning_tasks',
    label: 'Cleaning tasks',
    description: 'Cleaning tasks that are overdue',
    feature: 'cleaning',
    metric: summary => summary.overdueClean,
    metricLabel: 'Overdue cleans',
    dangerWhenPositive: true,
    action: (summary, vp) => summary.overdueClean > 0 && { label: `${summary.overdueClean} cleaning task${summary.overdueClean > 1 ? 's' : ''} overdue`, to: vp('/cleaning'), urgency: 'danger' },
  },
  critical_actions: {
    id: 'critical_actions',
    label: 'Critical actions',
    description: 'Open critical corrective actions',
    feature: 'corrective',
    metric: summary => summary.criticalActions,
    metricLabel: 'Critical',
    dangerWhenPositive: true,
    action: (summary, vp) => summary.criticalActions > 0 && { label: `${summary.criticalActions} critical action${summary.criticalActions > 1 ? 's' : ''} open`, to: vp('/corrective'), urgency: 'danger' },
  },
  pending_leave: {
    id: 'pending_leave',
    label: 'Time off requests',
    description: 'Pending leave requests that need review',
    feature: 'time_off',
    metric: summary => summary.pendingLeave,
    metricLabel: 'Leave',
    action: (summary, vp) => summary.pendingLeave > 0 && { label: `${summary.pendingLeave} leave request${summary.pendingLeave > 1 ? 's' : ''} pending`, to: vp('/time-off'), urgency: 'info' },
  },
  duties: {
    id: 'duties',
    label: 'Duties',
    description: 'Shift duties assigned and completed today',
    feature: null,
    metric: summary => summary.dutiesAssigned,
    metricLabel: 'Assigned',
    action: (summary) => summary.dutiesAssigned > 0 && summary.dutiesCompleted < summary.dutiesAssigned && {
      label: `${summary.dutiesAssigned - summary.dutiesCompleted} of ${summary.dutiesAssigned} duties in progress`,
      urgency: 'info',
    },
  },
}

export const ALL_TODAY_ITEM_IDS = Object.keys(TODAY_ITEM_REGISTRY)
